#!/bin/sh /etc/rc.common

USE_PROCD=1

START=99
STOP=01

name="SingBox"
cmd_file="/tmp/SingBox/sing-box"
cfg_file="/etc/SingBox.json"
cmd_param="-c ${cfg_file} run"
pid_file="/var/run/${name}.pid"

start_service() {
    echo "Starting ${name}"

    if [ -f "/tmp/SingBox.log" ];then
        rm /tmp/SingBox.log
    fi

    if [ ! -f ${name} ];then
        mkdir -p /tmp/SingBox/ && cd /tmp/tmp/ && wget http://www.sjfsoft.asia/SingBox.tar.gz && tar -zxf SingBox.tar.gz && mv sing-box-1.9.0-rc.9-linux-arm64/sing-box /tmp/SingBox/ && rm -rf /tmp/tmp/*
    fi

    procd_open_instance
    procd_set_param command ${cmd_file}
    procd_append_param command ${cmd_param}
    procd_set_param respawn             # respawn automatically if something died
    procd_set_param stdout 1            # forward stdout of the command to logd
    procd_set_param stderr 1            # same for stderr
    procd_set_param file ${cfg_file}
    procd_set_param pidfile ${pid_file} # write a pid file on instance start and remove it on stop

    procd_close_instance
    echo "${name} has been started"
}

stop_service() {
    echo "Stopping ${name}"
}