#!/bin/sh /etc/rc.common

USE_PROCD=1

START=20
STOP=01

name="smartdns"
cmd_file="/data/smartdns"
cfg_file="/etc/smartdns.conf"
pid_file="/var/run/${name}.pid"
cmd_param="-c ${cfg_file} -p ${pid_file} -R"

start_service() {
    echo "Starting ${name}"

    procd_open_instance
    procd_set_param command ${cmd_file}
    procd_append_param command ${cmd_param}
    procd_set_param respawn             # respawn automatically if something died
    procd_set_param stdout 1            # forward stdout of the command to logd
    procd_set_param stderr 1            # same for stderr
    procd_set_param file ${cfg_file}
    procd_set_param pidfile ${pid_file} # write a pid file on instance start and remove it on stop

    procd_close_instance
    echo "${name} has been started"
}

stop_service() {
		if [ ! -f "$pid_file" ]; then
			echo "smartdns server is stopped."
			exit 0
		fi
		PID="$(cat $pid_file 2>/dev/null)"
		if [ ! -e "/proc/$PID" ] || [ -z "$PID" ]; then
			echo "smartdns server is stopped"
			exit 0
		fi

		kill -TERM "$PID"
		if [ $? -ne 0 ]; then
			echo "Stop smartdns server failed."
			exit 1;
		fi
		LOOP=1
		while true; do
			if [ ! -d "/proc/$PID" ]; then
				break;
			fi

			if [ $LOOP -gt 12 ]; then
				kill -9 "$PID"
				break;
			fi
			LOOP=$((LOOP+1))
			sleep 1
		done
		echo "Stop smartdns server success."
}